### ISSUE TITLE
An alias "speckcatalog_db" was requested but no service could be found

### ISSUE THREAD

**Issue by dipakdotyadav** [speckcommerce/speck#39]
i was able to setup/install speckcommerce successfully on my local system the tables were created as well, but after completion when i browse the project it gives below error.

"An alias "speckcatalog_db" was requested but no service could be found."

please suggest.

**Comment by lukeocodes** [comment]
I get this same error.

**Comment by shipleyr** [comment]
'speckcatalog_db' is a service alias defined in https://github.com/speckcommerce/SpeckCatalog/blob/master/config/services/servicemanager.php#L44. The only place it's called is in an initializer just below. I wouldn't mind guessing that the actual problem is that a database config file has not been created in your autoload directory. In the directory config/autoload create a file called 'database.config.php' and put the below in it...

```
<?php
/**
 * Database connection parameters.
 */
return array(
    'db' => array(
        'dsn'       => 'mysql:dbname=<<DB_NAME>>;host=<<DB_HOST>>',
        'username'  => '<<DB_USERNAME>>',
        'password'  => '<<DB_PASSWORD>>',
    ),
);
```

*obviously replacing the <<>> bits with actual values and try it again.

**Comment by lukeocodes** [comment]
Exactly what I needed, thanks mate!
